// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pharma-themes/CliniqueBlanche.tsx": () => import("../components/mockups/pharma-themes/CliniqueBlanche.tsx"),
  "./components/mockups/pharma-themes/PrestigeModerne.tsx": () => import("../components/mockups/pharma-themes/PrestigeModerne.tsx"),
  "./components/mockups/pharma-themes/VertSante.tsx": () => import("../components/mockups/pharma-themes/VertSante.tsx")
};
